### ISSUE TITLE
Handle yaml parsing errors for experimental files

### ISSUE THREAD

**Issue by dandavies99** [ImperialCollegeLondon/Faraday-liionsden#132]
**Problem:** Currently the biologic parsing engine fails if the header cannot be parsed as yaml. e.g. in this example the 3rd line cannot be interpreted as a `key:value` pair:

```yaml
BT-Lab ASCII FILE
Nb header lines : 79                          

Battery Capacity Determination

Run on channel : B1 (SN 0358)
User : 
Ecell ctrl range : min = 0.00 V, max = 9.00 V
Safety Limits :
...
```

The easiest thing to do would probably be to catch this Exception (ScannerError) and resort to saving as a text block instead.
